DROP TABLE IF EXISTS user_roles CASCADE;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    id               integer generated by default as identity,
    name             varchar(128)            not null,
    email            varchar(128)            not null,
    password         varchar(256)            not null,
    primary key (id)
);

CREATE TABLE user_roles
(
    user_id integer not null,
    role    varchar(255)
);

INSERT INTO USERS (NAME, EMAIL, PASSWORD)
VALUES ('User1', 'user1@yandex.ru', 'password1'),
       ('User2', 'user2@yandex.ru', 'password2'),
       ('Admin', 'admin@gmail.com', 'admin');

INSERT INTO USER_ROLES (ROLE, USER_ID)
VALUES ('USER', 1),
       ('USER', 2),
       ('ADMIN', 3);